version: '3'
services:
  web:
    container_name: Rayonweb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - NODE_ENV=production
